sudo: required
services:
  - docker


before_install:
  - docker build -t blimblimboi/docker-react -f Dockerfile.dev . 


script:
  - docker run -e CI=true blimblimboi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-create
  env: "DockerCreate-env"
  bucket_name: "elasticbeanstalk-us-east-2-476536526137"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY